### PR TITLE
Add initial gherkin diff script

### PR DESCRIPTION
**Pull request by ianmarcinkowski**

### CODE REVIEW

**Comment by ianmarcinkowski** [comment]
There will be a refactor to turn this in to a more sane python package.

**Comment by minichate** [comment]
:+1:

**Comment by amcintosh** [comment]
Maybe an initial `requirements.txt`?

**Comment by ianmarcinkowski** [comment]
@g-- is working on a branch to improve the packaging.  We'll do the requrements.txt in that branch

**Pull request merged**
